message(STATUS "====================================================")
message(STATUS "&&&    found executable programme: 1_Delete_minimum")
add_executable(1_Delete_minimum 1_Delete_minimum.cpp)
message(STATUS "&&&    found executable programme: 2_SequentialList_inverse")
add_executable(2_SequentialList_inverse 2_SequentialList_inverse.cpp)
message(STATUS "&&&    found executable programme: 3_DOUBLE_PTR_Delete_same_value")
add_executable(3_DOUBLE_PTR_Delete_same_value 3_DOUBLE_PTR_Delete_same_value.cpp)
message(STATUS "&&&    found executable programme: 4_DOUBLE_PTR_Delete_period")
add_executable(4_DOUBLE_PTR_Delete_period 4_DOUBLE_PTR_Delete_period.cpp)
