message(STATUS "====================================================")
message(STATUS "&&&    found executable programme: Fibonacci_best")
add_executable(Fibonacci_best Fibonacci_best.cpp)
message(STATUS "&&&    found executable programme: Fibonacci_nonrecursive")
add_executable(Fibonacci_nonrecursive Fibonacci_nonrecursive.cpp)
message(STATUS "&&&    found executable programme: Fibonacci_recursive")
add_executable(Fibonacci_recursive Fibonacci_recursive.cpp)
