message(STATUS "====================================================")
message(STATUS "&&&    found executable programme: SequentialList_Basic_Definition")
add_executable(SequentialList_Basic_Definition SequentialList_Basic_Definition.cpp)
message(STATUS "&&&    found executable programme: SequentialList_Full_Definition")
add_executable(SequentialList_Full_Definition SequentialList_Full_Definition.cpp)
